language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
install:
    - composer install --no-interaction
    - composer require --no-interaction satooshi/php-coveralls:dev-master
script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --debug --verbose --coverage-clover build/logs/clover.xml
after_script:
    - vendor/bin/coveralls
notifications:
    email: false
